"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any

logger: logging.Logger = ...
class ChainManager:
    """Internal data store for the comparison graph. All attributes are private.
    Access is only through CrystalGraph's public API.
    """
    def __init__(self) -> None:
        ...
    
    def build(self, comparisons: list[dict[str, Any]], all_filenames: set[str] | None = ...) -> None:
        ...
    
    def apply_comparison(self, winner: str, loser: str) -> None:
        ...
    
    def compute_min_chains(self) -> list[list[str]]:
        ...
    
    def get_node_chain_length(self, filename: str) -> int:
        ...
    
    def get_min_chain_count(self) -> int:
        ...
    
    def enumerate_all_chains(self, max_chains: int = ..., max_depth: int = ...) -> list[list[str]]:
        ...
    
    def enumerate_top_chains(self) -> list[list[str]]:
        ...
    
    def is_redundant(self, u: str, v: str, skip_edges: set[tuple[str, str]] | None = ..., max_depth: int | None = ...) -> bool:
        ...
    
    def are_in_same_path(self, img1: str, img2: str, max_depth: int | None = ...) -> bool:
        ...
    
    def get_collapsable_pairs(self) -> list[tuple[str, str]]:
        ...
    


class NodeProxy:
    """Represents one image/node in the graph. Created on demand, zero overhead."""
    def __init__(self, chain: ChainManager, node_id: str) -> None:
        ...
    
    @property
    def filename(self) -> str:
        ...
    
    def is_top(self) -> bool:
        ...
    
    def is_bottom(self) -> bool:
        ...
    
    def get_links(self, better_than: bool = ..., worse_than: bool = ...) -> list[NodeProxy]:
        ...
    
    def get_chain(self, only_main: bool = ...) -> list[ChainProxy]:
        ...
    
    def get_position_in_chain(self) -> int:
        ...
    
    def get_component(self) -> ComponentProxy | None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class ChainProxy:
    """Represents one directed path (chain). Created from min chain cover results."""
    def __init__(self, chain: ChainManager, chain_id: int, node_list: list[str]) -> None:
        ...
    
    @property
    def id(self) -> int:
        ...
    
    @property
    def nodes(self) -> list[NodeProxy]:
        ...
    
    @property
    def length(self) -> int:
        ...
    
    @property
    def first(self) -> NodeProxy | None:
        ...
    
    @property
    def last(self) -> NodeProxy | None:
        ...
    
    def get_nodes(self, only_top: bool = ..., only_bottom: bool = ...) -> list[NodeProxy]:
        ...
    
    def node_position(self, node_id: str) -> int:
        ...
    
    def get_component(self) -> ComponentProxy | None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class ComponentProxy:
    """Represents one connected component."""
    def __init__(self, chain: ChainManager, comp_id: int) -> None:
        ...
    
    @property
    def id(self) -> int:
        ...
    
    @property
    def nodes(self) -> list[NodeProxy]:
        ...
    
    @property
    def size(self) -> int:
        ...
    
    def get_chains(self, minimal_required: bool = ...) -> list[ChainProxy]:
        ...
    
    def __repr__(self) -> str:
        ...
    


nodeTuple = tuple[NodeProxy, bool]
chainTuple = tuple[ChainProxy, list[nodeTuple]]
chainDict = dict[int, chainTuple]
class CrystalGraph:
    """Main graph API. All access through get_* methods returning proxy objects."""
    def __init__(self) -> None:
        ...
    
    def rebuild_from_database(self, images: list[dict[str, Any]] | None = ..., comparisons: list[dict[str, Any]] | None = ...) -> None:
        ...
    
    def apply_comparison(self, winner: str, loser: str) -> None:
        ...
    
    def invalidate_cache(self) -> None:
        ...
    
    def is_cache_stale(self) -> bool:
        ...
    
    def get_node(self, node_id: str | None = ...) -> NodeProxy | None:
        ...
    
    def get_node_chain_length(self, filename: str) -> int:
        ...
    
    def get_all_nodes(self, only_top: bool = ..., only_bottom: bool = ...) -> list[NodeProxy]:
        ...
    
    def get_chain(self, node_id: str | None = ..., chain_id: int | None = ...) -> ChainProxy | None:
        ...
    
    def get_all_chains(self) -> list[ChainProxy]:
        ...
    
    def get_all_sub_chains(self, max_chains: int = ..., max_depth: int = ...) -> list[ChainProxy]:
        ...
    
    def get_component(self, node_id: str | None = ..., component_id: int | None = ..., chain_id: int | None = ...) -> ComponentProxy | None:
        ...
    
    def get_all_components(self) -> list[ComponentProxy]:
        ...
    
    def get_all_links(self) -> list[tuple[NodeProxy, NodeProxy]]:
        ...
    
    def get_graph_stats(self) -> dict[str, Any]:
        ...
    
    def get_cache_info(self) -> dict[str, Any]:
        ...
    
    def is_redundant(self, u: str, v: str, skip_edges: set[tuple[str, str]] | None = ...) -> bool:
        ...
    
    def are_in_same_path(self, img1: str, img2: str) -> bool:
        ...
    
    def get_collapsable_pairs(self) -> list[tuple[str, str]]:
        ...
    
    def get_chains_map(self) -> dict[int, chainDict]:
        ...
    
    def get_duplicate_comparison_ids(self) -> list[int]:
        """Return a list of comparison record IDs that are duplicates.

        For each unique (canonical_pair, winner) combination, keeps the most recent
        record (by timestamp) and marks older duplicates for deletion.

        Handles both:
        - Same-direction duplicates: (a,b,winner=a) and (b,a,winner=a)
        - Exact duplicates: identical records appearing multiple times
        """
        ...
    
    def get_redundant_edges(self) -> set[tuple[str, str]]:
        """Return a set of directed edges (winner, loser) that are considered redundant.

        Redundancy rules implemented:
        - Self-links (u -> u) are redundant.
        - Transitively redundant edges: direct edge u->v is redundant if there exists
          an alternative path u -> ... -> v (length >= 2) ignoring the direct edge.
        - Contradictory double-links (a->b and b->a): keep the most recent winner
          (based on comparison timestamps) and mark the opposite edge as redundant.
        """
        ...
    


crystal_graph = ...
