from typing import Any, Tuple
from numpy import ndarray

# Minimal stubs for matplotlib.pyplot functions used in the project.

def figure(**kwargs: Any) -> Any: ...
def plot(*args: Any, **kwargs: Any) -> Any: ...
def xlabel(s: str, **kwargs: Any) -> Any: ...
def ylabel(s: str, **kwargs: Any) -> Any: ...
def title(s: str, **kwargs: Any) -> Any: ...
def grid(b: Any = True, **kwargs: Any) -> None: ...
def show() -> None: ...
def subplots(**kwargs: Any) -> Tuple[Any, Any]: ...
