"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from PIL import Image
from torch import Tensor

def remove_directory(directory_path: Path) -> None:
    ...

def remove_vectors() -> None:
    ...

def remove_models() -> None:
    ...

def export_image_batch(pil_images: list[Image.Image]) -> Tensor:
    ...

