"""
This type stub file was generated by pyright.
"""

import torch
import numpy as np
import numpy.typing as npt
from PIL import Image
from typing import Any
from tqdm import tqdm
from torch import nn
from torchvision import transforms
from .batch_sizer import BatchSizer

VectorList = list[list[float]]
BucketItems = list[tuple[int, str]]
BucketDict = dict[tuple[int, int], BucketItems]
ImageInput = str | Image.Image | torch.Tensor | npt.NDArray[np.uint8] | list[Any] | tuple[Any, ...]
class ImageConverter:
    @staticmethod
    def to_pil(arr: npt.NDArray[Any]) -> list[Image.Image]:
        ...
    
    @staticmethod
    def from_path(image_path: str) -> list[Image.Image]:
        ...
    
    @staticmethod
    def prepare(image: ImageInput) -> list[Image.Image]:
        ...
    
    @staticmethod
    def get_size_from_path(img_path: str) -> tuple[int, int]:
        ...
    


class VectorEncoder:
    _transform: transforms.Compose | None = ...
    @classmethod
    def get_transform(cls) -> transforms.Compose:
        ...
    
    @staticmethod
    def encode(images: list[Image.Image], model: nn.Module, vector_length: int, transform: transforms.Compose) -> VectorList:
        ...
    
    @staticmethod
    def run_test(model: nn.Module, batch_tensor: torch.Tensor, device: str) -> None:
        ...
    


class PathProcessor:
    @staticmethod
    def build_buckets(path_list: list[str]) -> BucketDict:
        ...
    
    @staticmethod
    def sort_buckets(buckets: BucketDict) -> dict[tuple[int, int], BucketItems]:
        ...
    
    @staticmethod
    def process_bucket(items: BucketItems, size: tuple[int, int], model: nn.Module, vector_length: int, transform: transforms.Compose, batch_sizer: BatchSizer, memory_usage: float, vectors: VectorList, pbar: tqdm, rebuild: bool = ...) -> tuple[int, int] | None:
        ...
    


class ImageVector:
    def __init__(self, name: str) -> None:
        ...
    
    def array_to_pil(self, arr: npt.NDArray[Any]) -> list[Image.Image]:
        ...
    
    def prepare_image_batch(self, image: ImageInput) -> list[Image.Image]:
        ...
    
    def create_image_vector_batch(self, current_batch: list[Image.Image]) -> VectorList:
        ...
    
    def test_batch(self, batch_tensor: torch.Tensor, device: str) -> None:
        ...
    
    def get_batch_size(self, width: int, height: int, rebuild: bool = ...) -> int:
        ...
    
    def create_vector_list(self, memory_usage: float = ..., rebuild: bool = ...) -> VectorList | None:
        ...
    
    def create_vector_list_from_paths(self, memory_usage: float = ..., rebuild_width: int = ..., rebuild_height: int = ...) -> VectorList | tuple[int, int]:
        ...
    


